- name: "EarFun Air Pro 4"
  type: "True Wireless Earbuds"
  description: "Premium earbuds with advanced ANC technology and exceptional 50-hour battery life. Perfect for commuting and travel."
  price: "79.99"
  rating: 4.5
  image: "/assets/images/products/air-pro-4.jpg"
  review_url: "/review/earfun-air-pro-4/"
  category: "earbuds"
  badge: "Best Overall"
  badge_type: "premium"
  anc: "Yes (Advanced ANC)"
  battery: "10h + 40h case"
  water_resistance: "IPX5"
  best_for: "Premium Experience"
  features:
    - "Hybrid ANC Technology"
    - "50-Hour Battery Life"
    - "LDAC Hi-Res Audio"
- name: "EarFun Free Pro 3"
  type: "Sports Earbuds"
  description: "Secure-fit earbuds designed for active lifestyles with sweatproof protection and enhanced bass response."
  price: "69.99"
  rating: 4.3
  image: "/assets/images/products/free-pro-3.jpg"
  review_url: "/reviews/earfun-free-pro-3.html"
  category: "earbuds"
  badge: "Best for Sports"
  badge_type: "sports"
  anc: "No"
  battery: "7h + 28h case"
  water_resistance: "IPX7"
  best_for: "Workouts, Running"
  features:
    - "Secure Ear Hooks"
    - "Sweatproof Design"
    - "Enhanced Bass"
- name: "EarFun Air Pro 3"
  type: "True Wireless Earbuds"
  description: "Excellent balance of features and price with hybrid ANC and long battery life for everyday use."
  price: "59.99"
  rating: 4.4
  image: "/assets/images/products/air-pro-3.jpg"
  review_url: "/reviews/earfun-air-pro-3.html"
  category: "earbuds"
  badge: "Great Value"
  badge_type: "value"
  anc: "Yes (Hybrid ANC)"
  battery: "9h + 36h case"
  water_resistance: "IPX5"
  best_for: "Commuting, Travel"
  features:
    - "Hybrid ANC"
    - "Long Battery Life"
    - "Premium Audio"
- name: "EarFun Wave Pro"
  type: "Over-Ear Headphones"
  description: "Hi-Res certified over-ear headphones with incredible 80-hour battery and premium comfort for extended listening."
  price: "49.99"
  rating: 4.4
  image: "/assets/images/products/wave-pro.svg"
  review_url: "/reviews/earfun-wave-pro/"
  category: "headphones"
  badge: "Premium Pick"
  badge_type: "premium"
  anc: "N/A"
  battery: "80 hours"
  water_resistance: "N/A"
  best_for: "Extended Listening"
  features:
    - "Hi-Res Audio Certified"
    - "80-Hour Battery"
    - "Over-Ear Comfort"
- name: "EarFun UBoom X"
  type: "Bluetooth Speaker"
  description: "Powerful portable speaker with 360° surround sound and waterproof design for outdoor adventures."
  price: "89.99"
  rating: 4.2
  image: "/assets/images/products/uboom-x.jpg"
  review_url: "/reviews/earfun-uboom-x.html"
  category: "speakers"
  badge: "Best Speaker"
  badge_type: "speaker"
  anc: "N/A"
  battery: "16 hours"
  water_resistance: "IPX7"
  best_for: "Outdoor Activities"
  features:
    - "360° Surround Sound"
    - "Waterproof Build"
    - "Long Battery Life"
- name: "EarFun Tune Pro"
  type: "Budget Earbuds"
  description: "Affordable earbuds that don't compromise on quality, featuring 40-hour battery and IPX7 waterproof rating."
  price: "39.99"
  rating: 4.1
  image: "/assets/images/products/tune-pro.jpg"
  review_url: "/reviews/earfun-tune-pro.html"
  category: "earbuds"
  badge: "Best Budget"
  badge_type: "budget"
  anc: "No"
  battery: "8h + 32h case"
  water_resistance: "IPX7"
  best_for: "Budget-Conscious Users"
  features:
    - "40-Hour Battery"
    - "IPX7 Waterproof"
    - "Gaming Mode"
